In [9]:
from pathlib import Path
import pandas as pd
import json

PROJECT_ROOT = Path("/home/jovyan/MSC_PROJECT")
DATA_DIR = PROJECT_ROOT / "data" / "avdeepfake1mpp"
METADATA_DIR = DATA_DIR / "metadata"
MANIFEST_DIR = DATA_DIR / "manifests"
EXTRACTED_VAL = DATA_DIR / "extracted" / "val" / "val"

val_meta_path = METADATA_DIR / "val_metadata.json"

with open(val_meta_path, "r") as f:
    data = json.load(f)

if isinstance(data, list):
    meta_df = pd.DataFrame(data)
elif isinstance(data, dict):
    meta_df = pd.DataFrame.from_dict(data, orient="index").reset_index()
    meta_df = meta_df.rename(columns={"index": "metadata_key"})
else:
    raise ValueError(f"Unexpected metadata type: {type(data)}")

print("Metadata shape:", meta_df.shape)
print("Columns:")
print(meta_df.columns.tolist())

display(meta_df.head(20))

Metadata shape: (77326, 11)
Columns:
['file', 'original', 'split', 'modify_type', 'audio_model', 'fake_segments', 'audio_fake_segments', 'visual_fake_segments', 'video_frames', 'audio_frames', 'video_model']

,file,original,split,modify_type,audio_model,fake_segments,audio_fake_segments,visual_fake_segments,video_frames,audio_frames,video_model
0,vox_celeb_2/id01358/_1nATum8x78/00030/fake_vid...,vox_celeb_2/id01358/_1nATum8x78/00030/real.mp4,val,both_modified,yourtts,"[[4.4, 4.64]]","[[4.4, 4.64]]","[[4.4, 4.64]]",161,102656,Talklip
1,vox_celeb_2/id01358/_1nATum8x78/00027/fake_vid...,vox_celeb_2/id01358/_1nATum8x78/00027/real.mp4,val,both_modified,yourtts,"[[0.92, 1.04]]","[[0.92, 1.04]]","[[0.92, 1.04]]",166,106880,Talklip
2,vox_celeb_2/id01358/_1nATum8x78/00025/real.mp4,VoxCeleb2/dev/mp4/id01358/_1nATum8x78/00025.mp4,val,real,None,[],[],[],139,89088,None
3,vox_celeb_2/id01358/atpminqC_AU/00046/fake_vid...,vox_celeb_2/id01358/atpminqC_AU/00046/real.mp4,val,both_modified,yourtts,"[[2.74, 2.92]]","[[2.74, 2.92]]","[[2.74, 2.92]]",154,99008,Talklip
4,vox_celeb_2/id01358/atpminqC_AU/00041/real.mp4,VoxCeleb2/dev/mp4/id01358/atpminqC_AU/00041.mp4,val,real,None,[],[],[],178,114688,None
5,vox_celeb_2/id01358/atpminqC_AU/00040/fake_vid...,vox_celeb_2/id01358/atpminqC_AU/00040/real.mp4,val,visual_modified,None,"[[0.48, 0.86]]",[],"[[0.48, 0.86]]",132,83968,Talklip
6,vox_celeb_2/id01358/atpminqC_AU/00049/fake_vid...,vox_celeb_2/id01358/atpminqC_AU/00049/real.mp4,val,visual_modified,None,"[[0.9, 1.28]]",[],"[[0.9, 1.28]]",134,86016,Talklip
7,vox_celeb_2/id01358/y0DqbqHdcko/00073/real.mp4,VoxCeleb2/dev/mp4/id01358/y0DqbqHdcko/00073.mp4,val,real,None,[],[],[],135,87040,None
8,vox_celeb_2/id01358/bc1_8aKIQ3c/00057/fake_vid...,vox_celeb_2/id01358/bc1_8aKIQ3c/00057/real.mp4,val,both_modified,yourtts,"[[2.4, 2.64]]","[[2.4, 2.64]]","[[2.4, 2.64]]",130,83968,Talklip
9,vox_celeb_2/id01358/hqGQLN6Kle0/00059/real.mp4,VoxCeleb2/dev/mp4/id01358/hqGQLN6Kle0/00059.mp4,val,real,None,[],[],[],126,80896,None
10,vox_celeb_2/id01358/hqGQLN6Kle0/00059/real_vid...,vox_celeb_2/id01358/hqGQLN6Kle0/00059/real.mp4,val,audio_modified,yourtts,"[[1.18, 1.38]]","[[1.18, 1.38]]",[],119,76736,None
11,vox_celeb_2/id01358/WpG_yFhiRLc/00019/real.mp4,VoxCeleb2/dev/mp4/id01358/WpG_yFhiRLc/00019.mp4,val,real,None,[],[],[],221,142336,None
12,vox_celeb_2/id01358/WpG_yFhiRLc/00019/fake_vid...,vox_celeb_2/id01358/WpG_yFhiRLc/00019/real.mp4,val,visual_modified,None,"[[4.34, 4.58]]",[],"[[4.34, 4.58]]",221,142336,Talklip
13,vox_celeb_2/id01358/CugjG1ZI4Cc/00005/fake_vid...,vox_celeb_2/id01358/CugjG1ZI4Cc/00005/real.mp4,val,visual_modified,None,"[[1.72, 2.1]]",[],"[[1.72, 2.1]]",176,112640,Talklip
14,vox_celeb_2/id06427/a4vLoBoPHZM/00129/real_vid...,vox_celeb_2/id06427/a4vLoBoPHZM/00129/real.mp4,val,audio_modified,yourtts_word,"[[0.68, 1.61]]","[[0.68, 1.61]]",[],236,151296,None
15,vox_celeb_2/id06427/_NDpLZg0j2w/00126/fake_vid...,vox_celeb_2/id06427/_NDpLZg0j2w/00126/real.mp4,val,visual_modified,None,"[[2.56, 2.92]]",[],"[[2.56, 2.92]]",167,107520,Talklip
16,vox_celeb_2/id06427/_NDpLZg0j2w/00127/fake_vid...,vox_celeb_2/id06427/_NDpLZg0j2w/00127/real.mp4,val,visual_modified,None,"[[4.98, 5.16]]",[],"[[4.98, 5.16]]",197,126976,Talklip
17,vox_celeb_2/id06427/Ec6wJyCWt8o/00048/fake_vid...,vox_celeb_2/id06427/Ec6wJyCWt8o/00048/real.mp4,val,both_modified,yourtts,"[[2.24, 2.84]]","[[2.24, 2.84]]","[[2.24, 2.84]]",161,103168,Talklip
18,vox_celeb_2/id06427/Ec6wJyCWt8o/00049/fake_vid...,vox_celeb_2/id06427/Ec6wJyCWt8o/00049/real.mp4,val,both_modified,yourtts,"[[0.12, 0.84]]","[[0.12, 0.84]]","[[0.12, 0.84]]",185,118400,Talklip
19,vox_celeb_2/id06427/8CpHO6zIqOg/00029/real_vid...,vox_celeb_2/id06427/8CpHO6zIqOg/00029/real.mp4,val,audio_modified,yourtts,"[[3.4, 3.72]]","[[3.4, 3.72]]",[],161,103552,None

In [10]:
videos = sorted(EXTRACTED_VAL.rglob("*.mp4"))

video_df = pd.DataFrame({
    "path": [str(p) for p in videos],
    "relative_path": [p.relative_to(EXTRACTED_VAL).as_posix() for p in videos],
    "filename": [p.name for p in videos],
    "file_size_bytes": [p.stat().st_size for p in videos],
})

print("Extracted videos:", len(video_df))
print(video_df["filename"].value_counts().head(20))

display(video_df.head(20))

Extracted videos: 77326
filename
real.mp4                        13365
fake_video_fake_audio.mp4       13315
real_video_fake_audio.mp4       13202
fake_video_real_audio.mp4       13157
fake_video_fake_audio_p1.mp4     4815
real_video_fake_audio_p1.mp4     4799
fake_video_real_audio_p1.mp4     4798
real_p1.mp4                      4512
fake_video_real_audio_p2.mp4      320
fake_video_real_audio_p3.mp4      319
fake_video_fake_audio_p3.mp4      317
real_video_fake_audio_p2.mp4      315
real_video_fake_audio_p3.mp4      315
fake_video_fake_audio_p2.mp4      314
fake_video_fake_audio_p4.mp4      308
real_video_fake_audio_p4.mp4      307
fake_video_real_audio_p4.mp4      306
fake.mp4                          199
00002_p1.mp4                       45
00003_p1.mp4                       43
Name: count, dtype: int64

,path,relative_path,filename,file_size_bytes
0,/home/jovyan/MSC_PROJECT/data/avdeepfake1mpp/e...,lrs3/1Hok1iGFNSk/00004/fake_video_fake_audio.mp4,fake_video_fake_audio.mp4,1524347
1,/home/jovyan/MSC_PROJECT/data/avdeepfake1mpp/e...,lrs3/1Hok1iGFNSk/00004/fake_video_real_audio.mp4,fake_video_real_audio.mp4,1517990
2,/home/jovyan/MSC_PROJECT/data/avdeepfake1mpp/e...,lrs3/1Hok1iGFNSk/00004/real.mp4,real.mp4,2223274
3,/home/jovyan/MSC_PROJECT/data/avdeepfake1mpp/e...,lrs3/1Hok1iGFNSk/00004/real_video_fake_audio.mp4,real_video_fake_audio.mp4,1527373
4,/home/jovyan/MSC_PROJECT/data/avdeepfake1mpp/e...,lrs3/2YPHJdq5QWM/00001/00001_p1.mp4,00001_p1.mp4,2450165
5,/home/jovyan/MSC_PROJECT/data/avdeepfake1mpp/e...,lrs3/2YPHJdq5QWM/00001/00001_p2.mp4,00001_p2.mp4,10595518
6,/home/jovyan/MSC_PROJECT/data/avdeepfake1mpp/e...,lrs3/2YPHJdq5QWM/00001/00001_p3.mp4,00001_p3.mp4,7519828
7,/home/jovyan/MSC_PROJECT/data/avdeepfake1mpp/e...,lrs3/2YPHJdq5QWM/00002/00002_p1.mp4,00002_p1.mp4,1572790
8,/home/jovyan/MSC_PROJECT/data/avdeepfake1mpp/e...,lrs3/2YPHJdq5QWM/00002/00002_p2.mp4,00002_p2.mp4,1321325
9,/home/jovyan/MSC_PROJECT/data/avdeepfake1mpp/e...,lrs3/2YPHJdq5QWM/00002/00002_p3.mp4,00002_p3.mp4,1339097
10,/home/jovyan/MSC_PROJECT/data/avdeepfake1mpp/e...,lrs3/2YPHJdq5QWM/00003/00003_p3.mp4,00003_p3.mp4,1605428
11,/home/jovyan/MSC_PROJECT/data/avdeepfake1mpp/e...,lrs3/31ojbLK0vU4/00001/fake_video_fake_audio.mp4,fake_video_fake_audio.mp4,864841
12,/home/jovyan/MSC_PROJECT/data/avdeepfake1mpp/e...,lrs3/31ojbLK0vU4/00001/fake_video_real_audio.mp4,fake_video_real_audio.mp4,855550
13,/home/jovyan/MSC_PROJECT/data/avdeepfake1mpp/e...,lrs3/31ojbLK0vU4/00001/real.mp4,real.mp4,1177852
14,/home/jovyan/MSC_PROJECT/data/avdeepfake1mpp/e...,lrs3/31ojbLK0vU4/00001/real_video_fake_audio.mp4,real_video_fake_audio.mp4,863705
15,/home/jovyan/MSC_PROJECT/data/avdeepfake1mpp/e...,lrs3/64fDIZiVSSM/00006/fake_video_fake_audio.mp4,fake_video_fake_audio.mp4,594304
16,/home/jovyan/MSC_PROJECT/data/avdeepfake1mpp/e...,lrs3/64fDIZiVSSM/00006/fake_video_real_audio.mp4,fake_video_real_audio.mp4,592523
17,/home/jovyan/MSC_PROJECT/data/avdeepfake1mpp/e...,lrs3/64fDIZiVSSM/00006/real.mp4,real.mp4,930863
18,/home/jovyan/MSC_PROJECT/data/avdeepfake1mpp/e...,lrs3/64fDIZiVSSM/00006/real_video_fake_audio.mp4,real_video_fake_audio.mp4,596284
19,/home/jovyan/MSC_PROJECT/data/avdeepfake1mpp/e...,lrs3/8PQc3M2HQSs/00002/fake_video_fake_audio.mp4,fake_video_fake_audio.mp4,1662375

In [11]:
PATH_COL = "file"
meta_df = meta_df.copy()
meta_df["relative_path"] = meta_df[PATH_COL].astype(str).map(normalise_path)

manifest = video_df.merge(
    meta_df,
    on="relative_path",
    how="left",
    suffixes=("", "_meta")
)

print("Manifest shape:", manifest.shape)
print("Rows missing metadata:", manifest[PATH_COL].isna().sum() if PATH_COL in manifest.columns else manifest.isna().all(axis=1).sum())

display(manifest.head())

Manifest shape: (77326, 15)
Rows missing metadata: 0

,path,relative_path,filename,file_size_bytes,file,original,split,modify_type,audio_model,fake_segments,audio_fake_segments,visual_fake_segments,video_frames,audio_frames,video_model
0,/home/jovyan/MSC_PROJECT/data/avdeepfake1mpp/e...,lrs3/1Hok1iGFNSk/00004/fake_video_fake_audio.mp4,fake_video_fake_audio.mp4,1524347,lrs3/1Hok1iGFNSk/00004/fake_video_fake_audio.mp4,lrs3/1Hok1iGFNSk/00004/real.mp4,val,both_modified,yourtts,"[[0.65, 1.15], [2.03, 2.25]]","[[0.65, 1.15], [2.03, 2.25]]","[[0.65, 1.15], [2.03, 2.25]]",455,290816,Talklip
1,/home/jovyan/MSC_PROJECT/data/avdeepfake1mpp/e...,lrs3/1Hok1iGFNSk/00004/fake_video_real_audio.mp4,fake_video_real_audio.mp4,1517990,lrs3/1Hok1iGFNSk/00004/fake_video_real_audio.mp4,lrs3/1Hok1iGFNSk/00004/real.mp4,val,visual_modified,None,"[[0.65, 0.97], [1.851, 2.151]]",[],"[[0.65, 0.97], [1.851, 2.151]]",452,288768,Talklip
2,/home/jovyan/MSC_PROJECT/data/avdeepfake1mpp/e...,lrs3/1Hok1iGFNSk/00004/real.mp4,real.mp4,2223274,lrs3/1Hok1iGFNSk/00004/real.mp4,lrs3/1Hok1iGFNSk/00004/real.mp4,val,real,None,[],[],[],451,288768,None
3,/home/jovyan/MSC_PROJECT/data/avdeepfake1mpp/e...,lrs3/1Hok1iGFNSk/00004/real_video_fake_audio.mp4,real_video_fake_audio.mp4,1527373,lrs3/1Hok1iGFNSk/00004/real_video_fake_audio.mp4,lrs3/1Hok1iGFNSk/00004/real.mp4,val,audio_modified,yourtts,"[[0.65, 1.15], [2.03, 2.25]]","[[0.65, 1.15], [2.03, 2.25]]",[],455,290816,None
4,/home/jovyan/MSC_PROJECT/data/avdeepfake1mpp/e...,lrs3/2YPHJdq5QWM/00001/00001_p1.mp4,00001_p1.mp4,2450165,lrs3/2YPHJdq5QWM/00001/00001_p1.mp4,None,val,real,None,[],[],[],1265,2231296,None

In [12]:
audio_audit_path = MANIFEST_DIR / "audio_audit_all_videos.csv"
audio_df = pd.read_csv(audio_audit_path)

audio_df["relative_path"] = audio_df["relative_path"].astype(str).map(normalise_path)

keep_audio_cols = [
    "relative_path",
    "has_audio_stream",
    "audio_decodable",
    "audio_codec",
    "sample_rate",
    "channels",
    "audio_duration",
]

keep_audio_cols = [c for c in keep_audio_cols if c in audio_df.columns]

manifest = manifest.merge(
    audio_df[keep_audio_cols],
    on="relative_path",
    how="left"
)

print(manifest.shape)
print("Audio decodable:")
print(manifest["audio_decodable"].value_counts(dropna=False))

(77326, 21)
Audio decodable:
audio_decodable
True     76928
False      398
Name: count, dtype: int64

/tmp/ipykernel_1760207/2928902489.py:2: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  audio_df = pd.read_csv(audio_audit_path)

In [16]:
print(meta_df.columns.tolist())

if "modify_type" in manifest.columns:
    print(manifest["modify_type"].value_counts(dropna=False))

['file', 'original', 'split', 'modify_type', 'audio_model', 'fake_segments', 'audio_fake_segments', 'visual_fake_segments', 'video_frames', 'audio_frames', 'video_model', 'relative_path']
modify_type
real               20220
visual_modified    19099
both_modified      19069
audio_modified     18938
Name: count, dtype: int64

In [14]:
def labels_from_modify_type(x):
    s = str(x).lower()

    if s == "real":
        return pd.Series({
            "binary_label": 0,
            "visual_fake": 0,
            "audio_fake": 0,
            "condition": "real"
        })

    visual_fake = int("visual" in s or "video" in s or "both" in s)
    audio_fake = int("audio" in s or "both" in s)

    if visual_fake == 1 and audio_fake == 1:
        condition = "fake_video_fake_audio"
    elif visual_fake == 1 and audio_fake == 0:
        condition = "fake_video_real_audio"
    elif visual_fake == 0 and audio_fake == 1:
        condition = "real_video_fake_audio"
    else:
        condition = "fake_unknown"

    return pd.Series({
        "binary_label": 1,
        "visual_fake": visual_fake,
        "audio_fake": audio_fake,
        "condition": condition
    })

label_df = manifest["modify_type"].apply(labels_from_modify_type)
manifest = pd.concat([manifest, label_df], axis=1)

print(manifest["condition"].value_counts(dropna=False))
print(manifest["binary_label"].value_counts(dropna=False))

condition
real                     20220
fake_video_real_audio    19099
fake_video_fake_audio    19069
real_video_fake_audio    18938
Name: count, dtype: int64
binary_label
1    57106
0    20220
Name: count, dtype: int64

In [17]:
manifest_path = MANIFEST_DIR / "full_val_labelled_manifest.csv"
manifest.to_csv(manifest_path, index=False)

print("Saved:", manifest_path)
print("Rows:", len(manifest))

Saved: /home/jovyan/MSC_PROJECT/data/avdeepfake1mpp/manifests/full_val_labelled_manifest.csv
Rows: 77326

In [ ]:
usable_manifest = manifest[
    (manifest["audio_decodable"] == True) &
    (manifest["binary_label"].notna())
].copy()

usable_path = MANIFEST_DIR / "avd1mpp_val_labelled_manifest_usable_multimodal.csv"
usable_manifest.to_csv(usable_path, index=False)

print("Usable multimodal rows:", len(usable_manifest))
print(usable_manifest["condition"].value_counts(dropna=False))
print("Saved:", usable_path)